trigger:
- master

pool:
  name: Hosted Windows 2019 with VS2019

steps:
- checkout: self
  submodules: true
- pwsh: node build.js
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'Build\Release'
    artifactName: 'BuildOutput'


- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: 'Build\Release\*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '009da52b-8101-4621-b2c5-70aea38754aa'
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: 'Build\Release\*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'eb54cffe-f9d3-4c8e-a086-9837e8131e6d/97becbd8-003d-44ac-975d-09ee5da34342'